### ISSUE TITLE
Record header support

### ISSUE THREAD

**Issue by larsroholm** [cloudhut/kowl#108]
We would like to see support for inspecting record headers like you can with Confluent Control Center.

We use headers for storing metadata about a record, e.g. service id (that produced the record), payload type and payload version (for values of type JSON).

**Comment by weeco** [comment]
PR is open which adds support for message header. We plan to add this in the next release but feel free to test this once the PR is merged :-).

**Comment by cjlotz** [comment]
Just a question around the PR.  We publish messages that only contain headers with no value.  Currently all these messages are shown as tombstone in the front-end.  Will this pull-request allow us to view the message headers?  
![image](https://user-images.githubusercontent.com/1300847/90312653-6a091780-df06-11ea-8237-98f0bbcb5210.png)

**Comment by weeco** [comment]
@cjlotz We are not entirely yet how we want to show the headers in the frontend - the frontend is yet to be done. Feel free to suggest how you would like the frontend to handle message headers?

Can you explain your usecase - I'm curious why you send messages without key and value but with headers. Maybe we can consider that usecase before we start working on the frontend.

**Comment by cjlotz** [comment]
@weeco Our use case is a topic that basically contains lightweight notifications of work that needs to be done between machines in a cluster.  The consumers on the different machines in the cluster listen in on the topic headers for the kind of work.  The different consumers are interested in specific headers and, if matched, they dispatch work into thread worker pools running on the different machines.   Within these worker pools, the actual message content is read from a persistent store using the message header information passed on by the consumer.

**Comment by weeco** [comment]
Thanks for explaining.

I have four options in my mind how we could show message headers:

1. We add another column which shows message headers which are collapsible (just like the value column). Adding another column however could kinda cause troubles due to the table/browser width.

2. We can add an option to toggle between the value column and the message headers so that either the value or the message headers can be inspected.

3. When collapsing the message value we also show the message headers (above the JSON viewer).

4. Message headers can only be inspected on demand. Users would need to click the "..." option in the message row and then click "Show headers"

![image](https://user-images.githubusercontent.com/23424570/90314333-3bde0480-df13-11ea-96a7-a85e081f5815.png)


What would you prefer @cjlotz @larsroholm ?

**Comment by cjlotz** [comment]
@weeco  Headers are not usually the primary info to view so I am happy with just being able to click something (like option 4) to view them or like option 2 to toggle between showing the value or headers.  Being able to add filters to only show the messages with specific headers are important for our use case though.

**Comment by larsroholm** [comment]
@weeco, I would like to second what @cjlotz said about being able to filter records based on information in the headers. This is also an important use case for us. It would allow us to view, e.g., records produced by a specific service, records with a given payload type, or records with a certain trace id.

I like your suggestions with regards to the front-end. I would prefer 3. So it would look something like this?
![mockup](https://user-images.githubusercontent.com/120086/90364911-40b2cd80-e065-11ea-9f3a-193a689bcf45.png)

I think that it would be best to make the header view collapsable (collapsed by default), so it takes up minimal screenreal estate. Each header value view would have to use a control equivalent to the one used for displaying the record values, as both can be of various types (we use JSON).

**Comment by weeco** [comment]
Thank you both for your feedbacks and suggestions in regards to the frontend, that definitely helps us. Don't be worried about using search filters, this functionality was quite easy to add and is already part of the PR: https://github.com/cloudhut/kowl/pull/113/files#diff-68ef69c49b9abc4a39e360e1ffea4293R228

Headers are passed as a map<string, any> to the JS interpreter so that you should be able to access them like this:

```js
if headers["producer"] === "order-service" {}
```

If you use JSON, Avro or anything else which we support for deserialization you can also access them:

```js
var producer = heeaders["producer"]
if producer.displayName == "order-service" {}
```

As soon as the frontend is added and the PR is merged to master we'll ping you so that you can review the approach :)

**Comment by weeco** [comment]
@larsroholm @cjlotz I just merged the PR which adds message header support. The message headers table will only be shown if they actually exist.

It doesn't look great right now but we'll certainly improve this in future updates.

If you want to you can test it now. An image for the version on the master branch has been built (each push builds a new image on quay).

**Comment by larsroholm** [comment]
@weeco, great work! I'll check it out tomorrow.

**Comment by larsroholm** [comment]
@weeco, I just tested with quay.io/cloudhut/kowl:master-2e549a96. I can see the headers just fine, which is nice. All header values are interpreted as strings, which is not always the case for us. We use JSON objects as header values. I don't know if you can apply the same heuristic/view to header values as you do to the record values, so that we are able to read them more easily. I know that Confluent Control Center also just displays header values as strings, so there might be a limitation there that I am not aware of. Either way it is a great addition which really helps us, so thanks a lot 👍

**Comment by weeco** [comment]
> We use JSON objects as header values. I don't know if you can apply the same heuristic/view to header values as you do to the record values, so that we are able to read them more easily. I know that Confluent Control Center also just displays header values as strings, so there might be a limitation there that I am not aware of. Either way it is a great addition which really helps us, so thanks a lot 👍

This is no technical limitation, theoretically the key could also be JSON because Kafka just stores it as byte array (luckily most libs don't support anything but string keys though).

The backend already supports that and if you inspect the websocket message in the chrome dev console, you will likely notice that the type of the message has already been recognized as JSON. We use the same deserialization logic for each header value as we use for the message value.

We weren't sure how we want to present that information as a table wouldn't be suitable for this anymore. We might use the same JSON viewer for message headers in the future. Feel free to submit a seperate issue so that we don't forget about supporting <string, object> pairs for message headers 👍
