### ISSUE TITLE
Setup without config file

### ISSUE THREAD

**Issue by sgvandijk** [cloudhut/kowl#138]
Since #40 a config file is required to run Kowl. Having the option to use such a file indeed makes sense when having to set many parameters, but makes it a bit more difficult to deploy Kowl. For instance, we run Kafka in AWS and would like to run a web UI in Fargate.

If we take Kafdrop for instance, we can just create a task description using the default Docker image and passing the broker addresses as an environment variable.

For Kowl we would have to build and deploy our own image with the config file baked in, or get it onto some external volume that is attached to the container. Those are not big efforts, but it does raise the threshold for giving Kowl a try from a few seconds of configuration in the AWS console to having to get into Dockerfile writing. 

My suggestion would be to still by default use a config file, but also allow using just flags or environment variables, which would then also override settings in the config file if they are in both, to allow easy reuse of the same Docker image with slightly different settings.

**Comment by weeco** [comment]
Hi @sgvandijk ,
I agree with your problem statement. We thought about this as well, but we wanted to avoid using bloated configuration libraries that can offer multiple configuration options. We wanted to keep it simple and not mess with this in our code. However your reasoning is valid and I'll just keep this issue open to await more feedback around this topic.

For quick testing you could use the docker compose we provide here: https://github.com/cloudhut/kowl/tree/master/docs/local . We also intend to create a docker image that spins up Kafka, Zookeeper and a service that produces some data so that you can test it against a demo cluster with data. That should make it as easy as possible to give Kowl a shot and if you like it, you should have enough time to deploy Kowl which is pretty simple as you don't even need a database or another persistence for it.

If you don't want to create a separate YAML file you could also simply use our helm chart or Terraform module to quickly deploy it into your cluster.

Have you had a chance to try Kowl?

**Comment by sgvandijkpp** [comment]
Thanks for the reply. I gave Kowl a try now, in the end I did go with creating a new image with a new entrypoint.sh that writes the config file using an environment:

```
#!/bin/sh
echo "kafka: {brokers: [$BROKERS]}" > /config.yml
./kowl --config.filepath=/config.yml
```

For a bit more about our use case and why this makes things easier for us: we use CDK to configure our infrastructure, including an MSK cluster. The broker addresses are generated partly randomly by AWS so not known beforehand, but retrievable. They can then be used anywhere else in the configuration, so we can pass them on in this case in the task definition for Kowl. This allows us to spin up and tear down a full temporary dev kafka+producers+consumers+kowl environment with a single `cdk deploy`/`cdk destroy` without having to know anything about the actual brokers (or about k8s/helm or terraform ;)).

**Comment by sgvandijk** [comment]
Thanks for the reply. I gave Kowl a try now, in the end I did go with creating a new image with a new entrypoint.sh that writes the config file using an environment:

```
#!/bin/sh
echo "kafka: {brokers: [$BROKERS]}" > /config.yml
./kowl --config.filepath=/config.yml
```

For a bit more about our use case and why this makes things easier for us: we use CDK to configure our infrastructure, including an MSK cluster. The broker addresses are generated partly randomly by AWS so not known beforehand, but retrievable. They can then be used anywhere else in the configuration, so we can pass them on in this case in the task definition for Kowl. This allows us to spin up and tear down a full temporary dev kafka+producers+consumers+kowl environment with a single `cdk deploy`/`cdk destroy` without having to know anything about the actual brokers (or about k8s/helm or terraform ;)).

**Comment by atoom** [comment]
I would like to add a `+1` on this feature request. A common convention seems to be to simply replace a dot-notated property syntax with underscores (for example Kafka Connect or Kong API Gateway) - e.g. `logger.level` -> `LOGGER_LEVEL` ?

I guess lists or even worse lists of objects could be a bit tricky to translate though ...

**Comment by azzamsa** [comment]
I second this. In our production machines, we avoid "files":  configuration or log files. Having such files will require additional steps and permission. It also harder for us to replicate services. Since we need to provide each machine with those config files.

**Comment by weeco** [comment]
The Kowl config requires here and there arrays which are not very handy to use using environment variables / flags or similar. Those who are interested in this feature could you describe what solution you would like to use?

You could still bake the config into your docker image and secrets can be overriden/set via arguments anyways.

**Comment by azzamsa** [comment]
Deploying without config files is our priority. But ...

> You could still bake the config into your docker image and secrets can be overriden/set via arguments anyways.

Yes, I did it for one of our services. I will do the same to Kowl then.

I just thought it's too simple for me to use additional file just to add these line:

``` yaml
kafka:
  brokers:
    - kafka1:9092
    - 13.93.xx.xx:9092

```

But, anyway.

**Comment by atoom** [comment]
We would like to avoid the following:
- Mounting a host volume into the container in order to be as stateless and secure as possible
- Building an image for each Kafka cluster - instead we want to be able to pass in the broker configuration via environment variables
- Adding tls certificates into the container image since that would require a new container build everytime we need to rotate the certificates

Two examples from the Kafka ecosystem that comes into mind are:

Bitnami packaging of Kakfa/Zookeeper:
- Execellent support for configuring pretty much everything via environment variables
- No support for injecting TLS certificates

Kafdrop:
- Injecting the whole config and tls/jks secrets via base64 encoded environment variables
- Less flexible becuase you have to inject the whole configuration and not just individual properties

A hybrid between Bitnami/Kafdrop would be ideal for us, i.e.:
- Allow for injection of individual configuration properties via environment variables (lists could be as simple as a comma-separated string?)
- Since Kowl is not Java-based, certificate files that are PEM-based certificates can be injected AS-IS (DER encoded files might have to be base64 encoded/decoded ?)

Since I mentioned security as an important factor above maybe I should highlight that we are aware that all the environment variables and therefor the certificate information will be visible when inspecting the container but we have counteracted this by hardening our container runtime configuration.

**Comment by weeco** [comment]
@atoom Thanks for the detailed feedback and ideas, that's very helpful :).

**Comment by sgvandijkpp** [comment]
To add an example outside of the Kafka ecosystem: IMO Airflow has done this well, where there is a configuration file, but every configuration setting [has a corresponding environment variable](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html) that can be used to set/override it.

The variables have consistent naming to handle subsections, and comma separated strings are used for lists. On top of that some have a `_CMD` version to specify a command to generate the value of the setting, for instance to fetch and combine a database hostname and the user credentials from an external secrets manager to use into a single connection string.

**Comment by sgvandijk** [comment]
To add an example outside of the Kafka ecosystem: IMO Airflow has done this well, where there is a configuration file, but every configuration setting [has a corresponding environment variable](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html) that can be used to set/override it.

The variables have consistent naming to handle subsections, and comma separated strings are used for lists. On top of that some have a `_CMD` version to specify a command to generate the value of the setting, for instance to fetch and combine a database hostname and the user credentials from an external secrets manager to use into a single connection string.
