### ISSUE TITLE
Question regarding automatic decoding

### ISSUE THREAD

**Issue by klefevre** [cloudhut/kowl#189]
Hi,

We're trying to send Avro encoded messages into Kafka.
We setup a schema registry that we connected to Kowl, so far so good, we can access the schema registry via Kowl and everything seems to work fine.

We have an issue regarding the messages received. We only see binary data, which is somewhat normal but we expected that Kowl would be able to decode them automatically using the schema registry.

The question is: Is Kowl should be able to decode automatically avro messages? If so, can you give us a hint of what we can do to make it work properly? 

Thank you,
Best

**Comment by weeco** [comment]
Hi,
your assumption that Kowl should automatically decode the messages is correct. All messages that are longer than 5 bytes (because that's the min length for an avro message - 1byte magic byte + 4bytes schema id) will be considered as potential avro message if a schema registry is configured, see: https://github.com/cloudhut/kowl/blob/master/backend/pkg/kafka/deserializer.go#L104-L208

If the schema registry doesn't have a schema for the given schema id in a message we can't decode the message. Can You work through the linked code (especially line 150-170) and see if you spot something that could fail in your specific case? Maybe pick some messages and check whether you can decode them as Kowl would decode the binary content and then check if magic byte is set and whether the schema registry has a schema for the decoded schema id?

**Comment by klefevre** [comment]
Hi @weeco thank you for your quick reply. We, indeed, missed the magic bytes part. We were not aware of the [wire format](https://docs.confluent.io/platform/current/schema-registry/serdes-develop/index.html#wire-format)... We were encoding in "raw avro". Now it works as expected :)

Thanks a lot. Keep up the good work!
Best

**Comment by weeco** [comment]
Thanks for the follow-up. Glad it does work for you now :).
