### ISSUE TITLE
Change truncation behavior for displaying long values

### ISSUE THREAD

**Issue by kcbaltz** [cloudhut/kowl#214]
Version: a02d696  May 4, 2021

When you are viewing messages and the body is JSON, values longer than a certain length are truncated by default with an ellipsis (...) added at the end.  I'm requesting a few fixes to this behavior

* increase the length before truncation occurs.  I think the current length is well below the width of even a small screen, so there's no value in the truncation.  An option to disable truncation entirely might be nice. 
* Right now, if you click the ... to expand the value and then try to select the entire text, it ends up truncating it again before you can copy the value.  This needs to be fixed although I'm not exactly sure how.  Maybe a +/- icon to the left of the value or clickable ... at the end only.  
* fInally, it should not truncate unless it will actually be shorter.  In the example below, you can see the value itself is actually a little shorter than the truncated version plus the ...'s

![image](https://user-images.githubusercontent.com/8388083/117895503-53180b80-b273-11eb-940a-1612abe4d969.png)

![image](https://user-images.githubusercontent.com/8388083/117895552-6fb44380-b273-11eb-9b1e-d963ddfb9234.png)

**Comment by rikimaru0345** [comment]
Hi, 
we're using react-json-view ( https://github.com/mac-s-g/react-json-view ) for displaying json.

I can (and definitely will 😄) increase the default cutoff length.
As for your other requests however, we don't really have an efficient way to implement those.
Stuff like that selection handling for example would require quite a bit of code changes.

We'd have to essentially create our own custom version of that library from the ground up.

That's something we don't currently have the time for since we're focussing on other features.
Usability is a big concern however, so actually doing what I said above (creating our own react-json-view library) will definitely be on our todo list eventually.

Currently there are two workarounds for selecting an expanded text without it collapsing again:
- We could activate small "copy to clipboard" buttons. Check out the demo of the library and hover over any of the json fields to see it in action: https://mac-s-g.github.io/react-json-view/demo/dist/
- Or you can start selecting on the line above (so the moment you press down the mouse button, it doesn't register as a click on the expanded region)

Let me know if maybe activating that copy to clipboard thing would be a good compromise for you.

**Comment by kcbaltz** [comment]
I like the copy to clipboard icon idea although it appears to want to include surrounding quotes for String values, which doesn't seem like the right idea to me.  E.g. the clipboard gets `"1234"` instead of `1234`

I didn't realize this was an external library.  I think I will open a separate issue there because this feels like an issue anyone using that library might have.   I did notice they have the ability to do ctrl/cmd-click to edit values which would also be a way to enable them for copying although it would be a workaround in the case of Kowl because you obviously can't edit Kafka messages.  Maybe they can add a modifier like "Hold shift when selecting to disable collapse".  

Thanks for your work on this project.  This is the only workable free Kafka client I've found for actually viewing messages and not just monitoring the system.

**Comment by rikimaru0345** [comment]
Hey there 😄 

First of all, I changed the default string collapse length from 40 to 200 characters. This is not yet in master but will be merged along with other stuff pretty soon.

Second, there are some good news. I had another look at the `onSelect` property that the lib provides.
It triggers when a user clicks on any **value** (and only value - there's no way to detect clicks on property names, at least not without quite a bit of work. but that should be fine for your issue at least, right?) Anyway, I can use that to do some custom handling.

So the only thing left to do is to figure out how **exactly** you'd like this to work.

The simplest idea would be to simply put the content the user clicks on into the clipboard.
There are a few problems with that though:
1. Its not obvious that this is a feature at all. People who'd like to use it aren't aware of it.
2. People who click on it on accident / for whatever reason get their clipboard contents overwritten.
3. This will still collide with the expand/collapse functionality for long strings and there is no way for me to "catch" and abort the event. That means even if I add some sort of additional requirement (e.g. that you hold down shift/ctrl or whatever while clicking) it will still expand/collapse the text (should it be too long).


For (1) and (2) I could probably require the user to hold some key, and show a small hint like this?
![image](https://user-images.githubusercontent.com/28133019/118092150-ff6d0580-b3cb-11eb-891c-3eb146acf75a.png)

And I think (3) shouldn't be too big of a problem. I might even be able to hack that in later (like making the return of the callback a bool that determines whether or not the click event aborts any additional handling).


What do you think?

**Comment by rikimaru0345** [comment]
Json values can now be copied with ctrl+click. A normal click will show a hint for that.
I've also added max string length as well as some other json viewer settings to the preferences.

Let me know what you think.

https://user-images.githubusercontent.com/28133019/118364919-d64e9f80-b59a-11eb-96d2-d881d948e3c7.mp4

https://user-images.githubusercontent.com/28133019/118364998-26c5fd00-b59b-11eb-8983-95921a24749b.mp4

**Comment by rikimaru0345** [comment]
I'll consider this issue done now.
But if there's anything not addressed here, definitely feel free to reopen or create a new issue or whatever 😄

**Comment by kcbaltz** [comment]
Sounds good.  Sorry for the delayed reply but I think your solution will be
very workable.  I did open an issue on the library itself but haven't heard
back yet.

Thanks,
KC
