### ISSUE TITLE
Translation of storage sizes is incorrect (1024^N vs. 1000^N)

### ISSUE THREAD

**Issue by amirabiri** [cloudhut/kowl#233]
I notice that in various areas in Kowl sizes appear weird. For example default segment size appears as 1.07GB.

This is incorrect as the default segment size is 1GB.

This is clearly a misrepresentation of 1024^3 - 1,073,741,824. If 1 GB in Kowl is accidentally taken as 1000^3 - then the result is

```
1,073,741,824
------------- = 1.073741824
1,000,000,000
```

**Comment by amirabiri** [comment]
https://docs.confluent.io/platform/current/installation/configuration/topic-configs.html#topicconfigs_segment.bytes

**Comment by weeco** [comment]
Hi @amirabiri ,
I think both are correct. What we show in the Kowl frontend is Gigabytes whereas Kafka uses Gibibytes. I'm unsure whether we should switch the representation from Gigabytes to Gibibytes. Is there any particular reason for either case?

**Comment by amirabiri** [comment]
Something doesn't sound right here, it is highly confusing. Any normal user that see 1GB would assume 1024^3 no?

**Comment by weeco** [comment]
No, Gigabyte and Gibibytes are different units. GB is short Gigabyte and GiB would be short for Gibibyte. I mean I see your point, that you would also like to have a possibility to convert the numbers to Gibibytes as the defaults are based on that, but in practice what Kowl shows looks fine to me.

1GB = 1 Gigabyte = 1000^3 = 1,000,000,000bytes
vs
1GiB = 1 Gibibyte = 1024^3 = 1,073,741,824bytes

Does that make sense?

**Comment by rikimaru0345** [comment]
> Something doesn't sound right here, it is highly confusing. Any normal user that see 1GB would assume 1024^3 no?

Actually no.
There is nothing special about data that would make the "metric prefixes" (kilo, mega, giga, tera, ...) work differently.
They have the same meaning for data as they have for physical units (meters, volts, etc), and they describe different powers of 10.

> Any normal user...
Try typing into google "1GB to bytes", it will show 10^9 bytes (1000000000) 


Currently Kowl uses the metric base (1000) and thus also the metric suffixes (KB/MB/GB/TB)
But we could add an option to the UI so that Kowl uses base 1024 and the corresponding suffixes "KiB", "MiB", "GiB", ...

**Comment by amirabiri** [comment]
Well, I've been coding for 20 and never noticed that KB/MB/GB are metric rather than 1024^N. And I'm pretty sure that I've seen places where it says KB / MB / GB and it was 1024^N.

I don't think this serves any purpose other than confusing users...
