### ISSUE TITLE
user experience for kafka connect

### ISSUE THREAD

**Issue by cobolbaby** [cloudhut/kowl#247]
![screencapture-localhost-8082-kafka-connect-2021-08-25-23_04_43](https://user-images.githubusercontent.com/11460848/130815835-58488b5e-f5f5-402f-948b-6d478e61b6a5.png)

- The number of list elements displayed exceeds the paging setting when the webpage first loads
- Table overflow
- The filter option box does not support state storage
- Not support sorting and filtering by connector status
- Not support jumping from the connector to its tasks

**Comment by rikimaru0345** [comment]
1, 3, 4: will fix 👍 
2: I'll add a maximum width for the column (full text will be shown with a popup on hover then)
5: By "from connector" you probably mean the connector details thing (with the connector config editor and the tasks list below it), right? However there is no "task details" view currently. I can add one if that would be useful to you. But what exactly would you like it to show other than the stuff in the table below the config editor?

Thanks for the feedback! 😄

**Comment by cobolbaby** [comment]
> But what exactly would you like it to show other than the stuff in the table below the config editor?

Sometimes we will notice that even though the connector is running, its task has failed. At this time, we need a restart button to restart a task individually. Just like [vue-connect](https://github.com/rueedlinger/vue-connect):

![屏幕快照 2021-08-26 上午12 14 15](https://user-images.githubusercontent.com/11460848/130827367-bff998e6-c346-4d65-a975-a6435eafad19.png)

**Comment by weeco** [comment]
Hey @cobolbaby ,
I think we addressed all your points (except table overflow) - if we missed something please let us know. We also added some logos for each connector. Would be nice if you could provide another screenshot once you are running the latest version - you seem to have a decent environment with lots of connectors :). You can find the tasks inside of the connectors details page and now we added the possibilty to restart the task.

Additionally we added a list of installed plugins inside of each Kafka connect cluster. You can find that in the newly added cluster details page. 

Looking forward to your feedback :). Latest docker tag is `master-edebcedf`

**Comment by cobolbaby** [comment]
>  if you could provide another screenshot once you are running the latest version

![screencapture-localhost-8082-kafka-connect-kafka-connect-ipt-2021-09-02-10_11_04](https://user-images.githubusercontent.com/11460848/131770336-fb368539-2a4c-49c6-bf3c-e37025ced0af.png)

The front-end basically meets the needs, but some details need to be confirmed. I don’t know if it meets expectations.

![2021-09-02 10-04-48屏幕截图](https://user-images.githubusercontent.com/11460848/131770349-f055dc8a-d592-4737-99d6-4aa3dde02a73.png)

- The filter condition can only show up when the user click the filter box. Does the list component support to display the filter conditions by default?
- The pagination list does not change with the input filter conditions.

**Comment by rikimaru0345** [comment]
> The front-end basically meets the needs, but some details need to be confirmed. I don’t know if it meets expectations.

Keep in mind I've only added those changes in a quick-and-dirty way for now.
There'll definitely be a polishing phase to improve the design of those Kafka Connect pages and iron out the bugs regarding pagination, search etc.


> The filter condition can only show up when the user click the filter box. Does the list component support to display the filter conditions by default?

Can you elaborate on that? What do you mean by filter conditions?
Some custom syntax maybe, like `class:"abc"`? 

Or do you simply mean that the search-box should be visible by default / when the table loads.

Currently the searchbox checks for the string/regex in all the text columns (name, class, type, state, cluster).

But I'm fully aware that there is still a lot that could/should be improved, for example:
- Making it obvious to the user what columns get searched
- Highlighting matched substrings in the table ![image](https://user-images.githubusercontent.com/28133019/131847892-e0caa57c-0cdd-4cd5-ae58-efcb7145d566.png)
- Maybe some custom syntax like described above
- An easier way to filter the other columns if they are "enum like" values 
![image](https://user-images.githubusercontent.com/28133019/131848087-1fde5367-a7ae-446b-82eb-13d39151897e.png)
- etc..


> The pagination list does not change with the input filter conditions.

Yep, that's a known bug. I'll get to it soon.

> If I want to add the logo of other connectors, how do I configure it?

Currently there is no way to manually configure that.
Speaking purely from a frontend standpoint, I could definitely add a dialog to add/customize the names and images for the connectors. But that would then be saved in the browser only, which I very much assume isn't really all that helpful.
We could probably make it configurable in the backend config-file; that'd not take much time I think (but then there'd be no frontend UI to change this config, since that would imply the changes are persisted somewhere in the backend). 
@weeco what do you think about that?

**Comment by weeco** [comment]
> If I want to add the logo of other connectors, how do I configure it?

I think it's good enough to rely on code contributions here. Sooner or later we should have a pretty complete list. Logos have to be added here: https://github.com/cloudhut/kowl/tree/master/frontend/src/assets/connectors and a mapping between connector class name (prefix) and the logo here: https://github.com/cloudhut/kowl/blob/master/frontend/src/components/pages/connect/helper.tsx (see connectormetadata)

**Comment by cobolbaby** [comment]
> Or do you simply mean that the search-box should be visible by default / when the table loads.

@rikimaru0345  Yes, this is exactly what I think.

> But I'm fully aware that there is still a lot that could/should be improved, for example:

Awesome.

> If I want to add the logo of other connectors, how do I configure it?

No matter where the configuration is stored, scalability is the primary consideration, and it should be convenient for contributors to add new items. Currently when adding a new connector configuration, contributors need to modify the front-end code. I think the front-end should traverse and load the connector configuration from a configuration list which can be stored in a file on the front-end or back-end.

**Comment by weeco** [comment]
> I think the front-end should traverse and load the connector configuration from a configuration list which can be stored in a file on the front-end or back-end.

Can you clarify that? What do you mean by loading the `connector configuration`. The only per connector configuration that is currently coded in the frontend is a mapping between a connector class name and the logo and I think it's fair to keep that as part of the code, rather than making it configurable dynamically on the user side.

If you mean creating new connectors via Kowl, there's a separate issue for that (#249 ) which you already saw though

**Comment by cobolbaby** [comment]
> If you mean creating new connectors via Kowl, there's a separate issue for that (#249 ) which you already saw though

No. 

> What do you mean by loading the connector configuration

Migrate the configuration from `.tsx` to a separate `.json` file

**Comment by rikimaru0345** [comment]
@cobolbaby can you test the latest version?
I'll add filtering for "enum columns" in all other tables tomorrow.

**Comment by cobolbaby** [comment]
I only saw the icon changes in the latest version. The feature improvements previously mentioned have not been implemented.

In addition, I find that the connector list does not support filtering now, I don't know if it is intentional.

![2021-09-15 11-40-46屏幕截图](https://user-images.githubusercontent.com/11460848/133366938-2acaa9ce-9aaa-4480-9e78-c3f2b36be1bb.png)

**Comment by rikimaru0345** [comment]
Should be fixed with https://github.com/cloudhut/kowl/commit/72f45e335020cb711ee3d30cd49570247e681636
All columns in all kafka-connect pages (and most other tables) should have filters for their enum columns now.

Currently the tables save their search-text, but they don't save the filters you selected or the sort-order of the columns.
I'll implement that soon.

After that I'll probably move on to other features, unless you have any other requests or suggestions; so let me know if there is anything 😄 

Also, there was the question of which columns exactly the text/regex-search searches in: I haven't been able to figure out a good way to represent that. Currently every table is different, some tables look for matches only in the "main" (name) column, others also include other columns... :/

**Comment by cobolbaby** [comment]
@rikimaru0345 There is indeed a necessary feature, that is, how to view the error message when a connector stops.

**Comment by weeco** [comment]
@cobolbaby As far as I know that kind of information is not accessible via the exposed REST API from a Connect cluster or am I wrong? I think you are supposed to look at the log messages of the connect cluster in that case, until Apache implements something for that (I wish that was possible too)

**Comment by weeco** [comment]
@cobolbaby Found it, @rikimaru0345 only has to add it into the frontend and we got that as well. Thanks for the awesome hint again

**Comment by cobolbaby** [comment]
![2021-09-26 11-38-16屏幕截图](https://user-images.githubusercontent.com/11460848/134792569-e732eba0-6705-4f1d-8993-69028b4ad812.png)

The status field of the task list does not match the actual status.

**Comment by rikimaru0345** [comment]
Yeah, that column was completely wrong actually.
Text in the popup wasn't formatted/capitalized either.
Should be fixed now!

**Comment by cobolbaby** [comment]
LGTM. Thank you for your support.
