### ISSUE TITLE
Feature Request: multi cluster support

### ISSUE THREAD

**Issue by coeckelm** [cloudhut/kowl#250]
Add possibility to configure multiple clusters and be able to switch between the clusters. 
This is usefull in larg environment where you have multiple clusters or even during migrations from 1 cluster to another cluster.

**Comment by weeco** [comment]
Hey,
we are aware that large corps operate multiple clusters but even though med- to large corps are our target audience we decided against multi cluster support.

The reasons for that are:
- Way more complex configuration (suddenly you can define multiple roles/rolebindings and configs (Brokers, SASL, TLS) in one Kowl instance)
- More complex code in handling multiple clusters in the backend as well as the frontend
- Frontend UI becomes more complex due to muliple cluster targets

We believe that it is still reasonable to deploy one Kowl instance per Kafka cluster. This is of course an opinionated decision and others may not like that. We made some thoughts and decided against that for the near future, which does not mean we will never change our opinion about this. Because it is unlikely that we will change our opinion about this I'll close the issue for now.
