### ISSUE TITLE
Please provide the binaries for linux server

### ISSUE THREAD

**Issue by rashminair90** [cloudhut/kowl#259]
We do not want to create a kubernetes cluster for this kafka UI, want to run it on linux server

**Comment by weeco** [comment]
Hi, you don't need to run Kowl on a Kubernetes cluster. Any environment that can run a docker container is good enough (you can also install docker on your linux server). However there's already an issue for providing binaries. Feel free to upvote it there so that we know there's a demand: https://github.com/cloudhut/kowl/issues/57

**Comment by rashminair90** [comment]
Can you give me the steps to install kowl on docker container?
