### ISSUE TITLE
Question about the consumer group used by Kowl and the possible impact on performance

### ISSUE THREAD

**Issue by OuesFa** [cloudhut/kowl#276]
Hello, 
Thanks for this soft which seems pretty cool as an alternative Web UI for Kafka. 
I like the consumer groups status and the granularity of the data. 
I have two main questions please:
- What is the consumer group used by kowl to read topics (how to make sure it doesn't use an existing one from another consumer)
- How do you ensure not to impact the kafka cluster performance while reading data for the UI users ? I mean, how exactly the Kowl consumer is behaving?  Also, in order to allow the user to look for an event using filters (which is great) without impacting the kafka cluster perfs.
Thanks

**Comment by weeco** [comment]
Hi @OuesFa ,
I'll try to answer your two questions:

1. Kowl does not use a consumer group to consume the Kafka records. Consumer groups are basically a different concept in Kafka that you are not forced to use when consuming records. Since we don't need the persistence of offsets we also do not use consumer groups.
2. I think that's nothing Kowl should be in charge of. Instead cluster operators can use quotas to ensure this. However what I've seen is that it isn't that easy to impact the kafka cluster performance. With enabled javascript filters in Kowl the bottleneck typically is the CPU resources that are available to Kowl. But even small clusters can handle consumers that pull tens of thousands Kafka records / second without issues so I wouldn't be too worried about that. 

Does that help?

**Comment by OuesFa** [comment]
Hi @weeco 👋 

Indeed it helps, thanks a lot for taking the time to explain 🙏
 
I'm curious about the mechanism allowing to consumer records without consumer groups ID, is the source code open for that part? Or maybe could you point me to a resource introducing the kafka consumer api allowing it? 

Regarding the second answer, I'm curious about how Kowl allows to filter data within a topic, I doubt it reads all the topic records and store them within memory in a data structure, so can you please provide me with more details about that behavior?

**Comment by weeco** [comment]
> I'm curious about the mechanism allowing to consumer records without consumer groups ID, is the source code open for that part? Or maybe could you point me to a resource introducing the kafka consumer api allowing it?

Yes it is, see: https://github.com/cloudhut/kowl/blob/ce13b2b75962ec8adfad318aea87861624a8dc2a/backend/pkg/kafka/consumer.go#L80-L200

> Regarding the second answer

We use a Javascript engine that evaluates javascript code for each Kafka record that we receive. This code will decide whether the record is sent to the frontend or dropped.

**Comment by OuesFa** [comment]
Thanks again 🙏 
Last question :) 
Is there a way to produce data using the Web UI ?

**Comment by weeco** [comment]
At the moment there isn't, but there's an open issue where someone asked for a feature to copy an existing record and possibly modify it's content. That's something we want to add as well. Feel free to create further feature requests as a GitHub issue if they don't exist yet :)

**Comment by OuesFa** [comment]
Actually it's a bit dangerous in prod envs even when using ACLs and quotas so maybe it's better not to add it 😅
Thanks a lot again!
I have another question regarding RBAC and licenses but I will look more into the docs and open a different PR if needed!
