### ISSUE TITLE
Any way to disable schema registry's subject level compatibility check

### ISSUE THREAD

**Issue by CsBigDataHub** [cloudhut/kowl#281]
Is there a way to disable schema registry's subject level compatibility check when compatibility is inherited?

It would be nice if we can view the schema on compatibility inherited subjects.

reference - https://github.com/cloudhut/kowl/blob/ac1eede1211df3525bcd886324d661d411cf98e5/backend/pkg/schema/client.go#L299

**Comment by weeco** [comment]
Hey @CsBigDataHub ,
I'm not very familiar with the schema registry. Could you provide a bit more description of what we should do / what currently does not work for you?

**Comment by CsBigDataHub** [comment]
Hey @weeco ,

The code I have pointed to in the issue description gets the configuration of the subject schema compatibility.
Have a look at the table in here - https://docs.confluent.io/platform/current/schema-registry/avro.html

Typically the default value is `BACKWARD` which is set globally and the same inherited by all the topics.
you can overwrite this value on subject level. 

`GET $SR-url/config` will give you compatibility set at a global level
`GET $SR-url/config/$subject_name` will give you compatibility set at a subject level

When we try to get the subject schema in KOWL, the process is trying to replicate the second `GET` command here, essential GET the compatibility setting for the subject. And if a subject just inherits the global value and the subject level compatibility setting is NOT overwritten, KOWL throws an expected error saying the compatibility setting is not configured for the subject. This fine as long as we can handle it and still display the schema. Right now all I see is the error.

Other way to handle this is, if the exception occurs the process can GET the global value and display it on the subject level.

Let me know if you need mopre info on this. I know it is a lot to take in. I wish I can help but I am not proficient with golang.

**Comment by weeco** [comment]
Thanks for the clear explanation, that helps a lot.

> Right now all I see is the error.

That obviously should not be the case. Could you take a look at the networks tab and show us how the JSON Response + status code for the relevant request looks like? An additional screenshot of the error shown in the frontend would help as well.

What you suggested to do instead makes sense to me. I think the backend should handle the upstream requests towards the schema registry. Regardless of the response the schema detail view should never fail (hence I was asking for more details around this).

**Comment by CsBigDataHub** [comment]
error when subject level schema compatibility is NOT set at the topic level-

console error -

```
magic_1  | {"level":"error","ts":"2021-11-22T18:16:02.705Z","msg":"Sending REST error","route":"/api/schemas/subjects/HCE-OCUDM-FACTCCV-key/versions/latest","method":"GET","status_code":503,"remote_address":"172.18.0.1:58128","public_error":"Schema overview request has failed. Look into the server logs for more details.","error":"failed to get compatibility for given subject: schema registry request failed: 40408 - Subject 'test_subject-key' does not have subject-level compatibility configured"}
```

UI error -

![image](https://user-images.githubusercontent.com/23665525/142914314-c86c18ff-c3f5-457a-aa59-388126424e43.png)

When subject level schema compatibility is set, UI or console do not show any error and every works.

![image](https://user-images.githubusercontent.com/23665525/142914724-a1151b14-1722-48be-b145-f73703278d8f.png)

**Comment by weeco** [comment]
Thanks @CsBigDataHub that's really helpful. I'm currently very busy, but we will try to get this fixed as soon as possible. I'll close the issue as soon as the fix is pushed :)

**Comment by weeco** [comment]
Hey @CsBigDataHub ,
I just had some time to look into this and it turned out that we already do what you've suggested. It will first try to get the subject level compatibility by requesting:

> GET $SR-url/config/$subject_name 

If that yields an error we will request the global compatibility and only if that fails we return an error. You can see that here: https://github.com/cloudhut/kowl/blob/645e3b4d55aeb7d7459491c4cfd5a5f42c61239e/backend/pkg/owl/schema_details.go#L35-L42

Anyways I just added a change that would return "UNKNOWN" as compatibility type just in case both requests fail. That would still be better than failing the whole request. Also I figured that there is an ambiguous log message. I have addressed this as well by logging the failed request at subject level only at the debug level (since this is often expected and users should not worry about that message). Only if both - the subject scoped request as well as the global config request fails a warn message will now be logged.

Overall this does not explain why your request fails. I think whenever this happens it should have logged an error message in the server. You might have missed the more important log messages here due to the log messages that are kind of expected. Additionally I do now propagate the error message to the frontend as well (in the past we thought it would be safer to not propagate error messages, but nowadays I think it's fine to do so). As far as I can tell the schema overview request should only fail if the schema registry's GET /subjects request has failed.

Could you give it another shot with the latest docker image that is currently being built against the master branch?

**Comment by CsBigDataHub** [comment]
Yes you are right. Using the latest docker image fixed it.
