### ISSUE TITLE
More than 1 space only display 1, should encode to HTML format

### ISSUE THREAD

**Issue by javalover123** [cloudhut/kowl#307]
More than 1 space only display 1, should encode to HTML format.

![image](https://user-images.githubusercontent.com/9191388/150287296-7c81a317-34ec-4535-a424-f5adf2a3e8f1.png)

**Comment by rikimaru0345** [comment]
Is the issue with the display? (It just not showing the extra spaces)
Or with the search? (it finding messages that should not match)

I am assuming this is only about the display, right?

At least for the filter-**button** this is actually intentional, as we want to show as much text as possible there. So preview of the filter text will show text even across linebreaks.

So filter code:
```
a
b
c
``` 
Should display `a b c` in the filter preview button.

But I can change the shown spaces for the value column.

**Comment by javalover123** [comment]
Such as 4 space just display 1 space.

Message is: {"en":"a b  c   d    e","cn":"我爱你中国"}
Filter is: return value.en.includes("d    e")

**Comment by javalover123** [comment]
> Is the issue with the display? (It just not showing the extra spaces) Or with the search? (it finding messages that should not match)
> 
> I am assuming this is only about the display, right?
> 
> At least for the filter-**button** this is actually intentional, as we want to show as much text as possible there. So preview of the filter text will show text even across linebreaks.
> 
> So filter code:
> 
> ```
> a
> b
> c
> ```
> 
> Should display `a b c` in the filter preview button.
> 
> But I can change the shown spaces for the value column.

value column, including the json view.

![image](https://user-images.githubusercontent.com/9191388/150707837-da648e74-7ba6-4284-a4c2-0ba34cac7bbf.png)
