### ISSUE TITLE
Add tooltips for Consumer Group states

### ISSUE THREAD

**Issue by weeco** [cloudhut/kowl#45]
The consumer group overview lists all consumer groups along with it's group state. For users it might not be clear what each state means. One could improve this by adding a tooltip for all possible group states.

![w9dpthI](https://user-images.githubusercontent.com/23424570/82753300-e0452480-9dc4-11ea-8e17-147a8c222fd3.png)

**Existing group states are:**

- Stable - Consumer group has members which have been assigned partitions
- Empty - Consumer group does not have any members
- Unknown - Group state is not known
- Dead - Consumer group does not have any members and it's metadata has been removed
- Preparing Rebalance - A reassignment of partitions is required. Members are asked to stop consuming so that rebalancing can take place
- Completing Rebalance - Kafka assigns partitions to group members

Additional information for reference: https://chrzaszcz.dev/2019/06/kafka-rebalancing/ (nice blogpost describing consumer group states)

**Icons are matched here:** 

https://github.com/cloudhut/kowl/blob/master/frontend/src/components/pages/GroupDetails.tsx#L300-L305 (this list is not complete and requires more states to be added)

**Comment by rikimaru0345** [comment]
just need to warp a `Popover` around [this part](https://github.com/cloudhut/kowl/blob/master/frontend/src/components/pages/GroupDetails.tsx#L310)

**Comment by rikimaru0345** [comment]
Example usage of a popover:
https://github.com/cloudhut/kowl/blob/master/frontend/src/components/pages/topic/List.tsx#L101


If you want to show a "list" describing all possible icons/states (instead of just describing the icon the user is currently hovering over), use `QuickTable` to easily align descriptions and values; like here for example:
https://github.com/cloudhut/kowl/blob/master/frontend/src/components/pages/topic/List.tsx#L90
