### ISSUE TITLE
Show processing stats after each search

### ISSUE THREAD

**Issue by weeco** [cloudhut/kowl#85]
When using filters we get every second a progress update that shows the number of processed messages and amount of bytes. When the search request is done the information is not accessible anymore. As a user I'd like to see these stats for my last search until I trigger a new one.

**Comment by rikimaru0345** [comment]
Currently a `progressUpdate` message is sent once every second. So in order to show the complete stats we need the final numbers in the `done` message.

The `done` message could (should) be expanded with more interesting information.
Maybe how many messages were read by the backend from each partition, and how many of those messages passed the filter.
```
{
    type: 'done',
    partitionStats: {
        1: { read: 2600, matched: 53 },
        ...
    },
    elapsedMs: 12345,
    totalReadBytes: ..., // received from kafka
    totalSentBytes: ..., // sent to frontend
    totalFilterCpuMs: ..., // sum of time taken to filter messages (bad metric though. cpu cycles spent in interpreter would be better) 
}
```

**Comment by weeco** [comment]
Update: The `done` message already contains the final stats. Thus I'll remove the backend label.
