### ISSUE TITLE
Support for Avro

### ISSUE THREAD

**Issue by rikimaru0345** [cloudhut/kowl#9]
As mentioned in #8 :

- [ ] Avro data has to be transformed into Json in the backend. 

- [ ] When sending messages to the frontend, the original format of the message must be sent along as a simple description. Something like `sourceFormat:"avro"`.

- [ ] The frontend has to display the source format.

**Comment by darrenhaken** [comment]
has this feature started development yet? We'd love this!

**Comment by weeco** [comment]
@darrenhaken Yes, will most likely be part of 1.2

It's a bit more work because there's no schema registry support for Go, but that's not a problem.

**Comment by darrenhaken** [comment]
That's great, is 1.2 the next release?

I have only stumbled across Kowl today, it looks like a great OSS tool 👍

**Comment by weeco** [comment]
Yes, v1.1 is the latest version and we comply with semver 2. Feel free to subscribe to this issue, we always try to have the master branch in a deployable state so once this issue is closed you could immediately try it - images from master branch are automatically built on each push as well :-). 

Thank you, I'm glad you like the work

**Comment by weeco** [comment]
@darrenhaken I just merged the PR which adds support for avro. Feedback is highly appreciated, you can test it right now by deploying the version from #master (see: https://quay.io/repository/cloudhut/kowl?tab=tags).
